name: Auto-approve PR

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  approve:
    name: Auto-approve
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'krieger2501'

    permissions:
      pull-requests: write

    steps:
      - uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              event: 'APPROVE',
            });
